---
title: "Research Outputs"
---

# Publications  

- McHutchison, C.A., Costello, E., Ryan, M., McIntosh, A., Heverin, M., Newton, J., Chandran, S., Pal, S., Hardiman, O., Pender, N., & Abrahams, S. **(under review)**. Cognition, behaviour, and psychiatric symptoms in Motor Neuron Disease kindreds. European Journal of Neurology.

- McHutchison, C., Wuu, J., McMillan, C., Rademakers, R., Statland, J., Ravits, J., Wu, G., Rampersaud, E., Myers, J.R, Hernandez, J.P., The CReATe Consortium, Abrahams, S., & Benatar, M. (2023). The Temporal course of cognitive and behavioural changes in Motor Neuron Diseases. Journal of Neurology, Neurosurgery and Psychiatry. Epub ahead of print. DOI:10.1136/jnnp-2023- 331697

- Costello, E., Ryan, M., Donohoe, B., Kavanagh, C., Pinto-Grau, M., Doherty, M., McLaughlin, R.L., McHutchison, C.A., Abrahams, A., Heverin, M, Hardiman, O., & Pender, N.P. (2023). Cognitive and neuropsychiatric endophenotypes in Amyotrophic Lateral Sclerosis. Brain Communications. DOI:10.1093/braincomms/fcad166

- Benatar, M., Granit, V., Andersen, P.M., Grignon, A., McHutchison, C., Cosentino, S., Malaspina, A., & Wuu, J. (2022). Mild motor impairment as prodromal state in amyotrophic lateral sclerosis: A new diagnostic entity. Brain. DOI:10.1093/brain/awac185.

- Clancy, U., Makin, S.D.J., McHutchison, C.A., Cvoro, V., Chappell, F.M., Hernández, M.D.C.V., et al. (2022). Impact of small vessel disease progression on long-term cognitive and functional changes after stroke. Neurology, DOI: 10.1212/WNL.0000000000200005

- Benatar, M., Wuu, J., McHutchison, C., Postuma, R.B., Boeve, B.F., Petersen, R., et al. (2021). Preventing amyotrophic lateral sclerosis: Insights from pre-symptomatic neurodegenerative diseases. Brain. DOI: 10.1093/brain/awab404.

- McHutchison, C., Blair, G.W., Appleton, J.P., Chappell, F.M., Doubal, F., Bath, P.M., & Wardlaw, J.M. (2020). Cilostazol for secondary prevention of stroke and cognitive decline: Systematic review and meta-analysis. Stroke, 51(8), 2374-2385. DOI: 10.1161/STROKEAHA.120.029454. 

- McHutchison, C.A., Leighton, D.J., McIntosh, A., Colville, S., Cleary, E., Warner, J., Porteous, M., Chandran, S., Pal, S., & Abrahams, S. (2019). Relationship between neuropsychiatric disorders and cognitive and behavioural change in MND. Journal of Neurology, Neurosurgery and Psychiatry, 91(3). DOI: 10.1136/jnnp-2019-321737.

- McHutchison, C.A., Chappell, F.M., Makin, S., Shuler, K., Wardlaw, J.M., & Cvoro, V. (2019). Stability of estimated premorbid cognitive ability over time after minor stroke and its relationship with post-stroke cognitive ability. Brain Sciences, 9(17). DOI: 10.1177/1747493017730780.

- McHutchison, C.A., Cvoro, V., Makin, S., Chappell, F.M., Schuler, K., & Wardlaw, J.M. (2018). Functional, cognitive and physical outcomes three-years after minor lacunar or cortical ischaemic stroke. Journal of Neurology, Neurosurgery and Psychiatry. DOI: 10.1136/jnnp-2018-319134

- Backhouse, E., McHutchison, C., Cvoro, V., Shenkin, S., & Wardlaw, J.M. (2018). Cognitive ability, education and socioeconomic status in childhood and risk of post-stroke depression in later life: A systematic review and meta-analysis. PLoS One, 13(7). DOI:10.1371/journal.pone.0200525

- Loos, C.M.J., McHutchison, C., Cvoro, V., Shenkin, S., & Wardlaw, J. (2018). The relation between total cerebral small vessel disease burden and gait impairment in patients with minor stroke. International Journal of Stroke, 13(5), 518-524. DOI: 10.1177/1747493017730780

- McHutchison, C.A., Backhouse, E.V., Cvoro, V., Shenkin, S.D., & Wardlaw, J.M. (2017). Education, socioeconomic status and intelligence in childhood as risk factors for stroke in later life: A meta-analysis. Epidemiology, 28(4), 608-618. DOI: 10.1097/EDE.0000000000000675

- Backhouse, E.V., McHutchison, C.A., Cvoro, V., Shenkin, S.D., & Wardlaw, J.M (2017). Early life risk factors for cerebrovascular disease: A systematic review and meta-analysis. Neurology, 88(10), 976-984. DOI: 10.1212/WNL.0000000000003687

- Backhouse, E.V., McHutchison, C.A., Cvoro, V., Shenkin, S.D., & Wardlaw, J.M. (2015). Early life risk factors for stroke and cognitive impairment. Current Epidemiological Reports, 2, 172-179. DOI: 10.1007/s40471-015-0051-7

# Conferences and presentations  

- Abrahams, S., & McHutchison, C. (2023). Stratification by Cognition: Pros and Cons. Invited speaker at the World Federation of Neurology Stratification in Clinical Trials Working Group, Basel, Switzerland. 

- McHutchison, C. (2023). The temporal course of cognitive and behavioural impairment in Motor Neuron Diseases. Invited speaker at the European Network to Cure ALS (ENCALS), Barcelona, Spain.

- McHutchison, C., Wuu, J., Cosentino, S., Abrahams, S., & Benatar, M. (2023). Prodromal cognitive and behavioural deficits in amyotrophic lateral sclerosis and frontotemporal dementia (ALS/FTD): Preliminary findings from the Pre-fALS study. Oral presentation at the British Neuropsychological Society Spring Meeting, London, UK.

- McHutchison, C., & Abrahams, S. (2023). Assessing psychiatric symptoms in neurodegenerative disease: Development of a new measurement tool. Pre-registration poster presentation at the British Neuroscience Association Festival, Brighton, UK.

- McHutchison, C., Wuu, J., Cosentino, S., Abrahams, S., & Benatar, M. (2023) Prodromal cognitive and behavioural impairment in ALS-FTSD: Application of the MCI/MBI conceptual framework. Oral presentation at the 2nd International Pre-symptomatic ALS Workshop, Miami, USA.

- McHutchison, C., Abrahams, S., Wuu, J., Cosentino, S., & Benatar, M. (2022). Defining mild cognitive and behavioural impairment in pre-symptomatic ALS/FTD. ePoster presentation at the 32nd MND Association Virtual Symposium.

- McHutchison, C.A., Abrahams, S., Wuu, J., Benatar, M. (2022).  Prodromal Cognitive and Behavioural Impairment: A Conceptual Framework. Oral presentation at the Clinical Research in ALS and Related Disorders for Therapeutic Development (CReATe) Virtual Annual Meeting.

- McHutchison, C., Abrahams, S., Wuu, J., Cosentino, S., & Benatar, M. (2022). Pre-symptomatic mild cognitive and behaviour impairment in ALS-frontotemporal spectrum disorder (ALS-FTSD): A conceptual framework. Oral presentation at the European Network to Cure ALS (ENCALS), Edinburgh, UK.

- McHutchison, C.A., Wuu, J., Abrahams, S., & Benatar, M. (2021). Patterns of longitudinal cognitive and behavioural change in ALS/MND. ePoster presentation at the 31st MND Association Virtual Symposium. 

- McHutchison, C.A., McIntosh, A., Ryan, M., Costello, E., Heverin, M., Newton, J., Pal, S., Chandran, S., Hardiman, O., & Abrahams, S. (2021). Are psychiatric symptoms in people with MND and their kindreds associated with cognition and behaviour in people with MND? Oral presentation at the European Network to Cure ALS (ENCALS), Virtual conference.

- McHutchison, C.A., Wuu, J., Abrahams, S., Benatar, M. (2021).  Does cognition and behaviour change over time in ALS? Oral presentation at the Clinical Research in ALS and Related Disorders for Therapeutic Development (CReATe) Virtual Annual Meeting.

- McHutchison, C.A., McIntosh, A., Ryan, M., Costello, E., Heverin, M., Newton, J., Pal, S., Chandran, S., Hardiman, O., & Abrahams, S. (2020). Are psychiatric symptoms and disorders associated with cognitive and behavioural abnormalities in ALS? ePoster presentation at the 30th MND Association Virtual Symposium. 

- McHutchison, C.A., Leighton, D., Newton, J., on behalf of the CARE-MND Consortium, McIntosh, A., Chandran, S., Pal, S., & Abrahams, S. (2018). A family history of depression and anxiety predicts cognitive and behavioural changes in MND. Oral presentation at the 29th MND Association Symposium, Glasgow, UK.

- McHutchison, C.A., McIntosh, A, Ryan, M., Costello, E., Heverin, M., Hardiman, O., & Abrahams, S. (2018). Behavioural changes in MND are associated with symptoms of neuropsychiatric disorders in first and second-degree family members. Poster presentation at the 29th MND Association Symposium, Glasgow, UK.
